name: Continuous Integration

on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install cpp
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc clang

      - name: Run cpp tests
        run: |
          make -C cpp_00/ex00
          ./cpp_00/ex00/megaphone
          ./cpp_00/ex00/megaphone "teste_1"
          make -C cpp_00/ex01
          ./cpp_00/ex01/phonebook
          EXIT
          make -C cpp_01/ex00
          ./cpp_01/ex00/Zombie
